# Generated by Django 3.1 on 2022-02-20 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deposits',
            old_name='User',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='notifications',
            old_name='User',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='withdrawal',
            old_name='User',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='deposits',
            name='comments',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
