# Generated by Django 3.1 on 2022-02-20 20:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20220220_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposits',
            name='date_generated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='notifications',
            name='date_generated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='date_generated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='deposits',
            name='comments',
            field=models.CharField(default='Unconfirmed', max_length=40),
        ),
        migrations.AlterField(
            model_name='profile',
            name='wallet',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
