# Generated by Django 3.1 on 2022-02-20 20:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0003_auto_20220220_1233'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='deposits',
            new_name='deposits_table',
        ),
        migrations.RenameModel(
            old_name='notifications',
            new_name='notifications_table',
        ),
        migrations.RenameModel(
            old_name='withdrawal',
            new_name='withdrawal_table',
        ),
    ]
