# Generated by Django 3.1 on 2022-02-22 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20220220_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='wallet_table',
            fields=[
                ('wallet_id', models.AutoField(primary_key=True, serialize=False)),
                ('wallet_address', models.CharField(max_length=80)),
                ('wallet_coin', models.CharField(max_length=16)),
            ],
        ),
    ]
