# Generated by Django 3.1 on 2022-02-25 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_wallet_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='history_table',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_address', models.CharField(max_length=80)),
                ('history_coin', models.CharField(max_length=16)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='wallet',
            field=models.CharField(blank=True, default='12345667788', max_length=64),
        ),
        migrations.AlterField(
            model_name='withdrawal_table',
            name='comments',
            field=models.CharField(default='Unconfirmed', max_length=40),
        ),
        migrations.AlterField(
            model_name='withdrawal_table',
            name='status',
            field=models.CharField(default='Pending', max_length=10),
        ),
    ]
